#!/usr/bin/php
<?php

use Symfony\Component\Console\Application;
use Timpack\Travian\CommandRegistry;

require_once(dirname(__DIR__) . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php');

$application = new Application();

$commandRegistry = CommandRegistry::getInstance()->getCommands();
foreach ($commandRegistry as $_commandClass) {
    $application->add(new $_commandClass());
}

$application->run();
